# Generated by Django 4.2.1 on 2023-06-26 11:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_logo', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image_1', models.ImageField(upload_to='event_image_1/')),
                ('image_2', models.ImageField(upload_to='event_image_2/')),
                ('image_3', models.ImageField(upload_to='event_image_3/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField()),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='event_image_1/')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_image', models.ImageField(upload_to='Testimonial/')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='subcategory/')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('image_one', models.ImageField(upload_to='products/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('youtube', embed_video.fields.EmbedVideoField()),
                ('slug', models.SlugField(unique=True)),
                ('des_title_one', ckeditor.fields.RichTextField()),
                ('des_one', ckeditor.fields.RichTextField()),
                ('des_title_two', ckeditor.fields.RichTextField()),
                ('des_two', ckeditor.fields.RichTextField()),
                ('des_title_three', ckeditor.fields.RichTextField()),
                ('des_three', ckeditor.fields.RichTextField()),
                ('des_title_four', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_four', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_title_five', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_five', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_title_six', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_six', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_title_seven', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_seven', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_title_eight', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_eight', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_title_nine', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_nine', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_title_ten', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('des_ten', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('related_products', models.ManyToManyField(blank=True, to='app.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post')),
            ],
        ),
    ]
